/*****************************************************
 * Executable:   Deque_as_array_driver
 * Author:  Douglas Wilhelm Harder
 * Copyright (c) 2006-8 by Douglas Wilhelm Harder.  All rights reserved.
 *
 * DO NOT EDIT THIS FILE
 *
 * Create an instance of the Deque_as_array<int> class
 * and call the member function run().
 *
 * The member function run() will interpret the
 * input appropriately and exit when the interpreter
 * receives either the command 'exit' or and
 * end-of-file.
 *****************************************************/

#include "Deque_as_array_tester.h"
#include "Deque_as_array.h"
#include <iostream>

using namespace std;
int main() {
	Deque_as_array_tester<int> tester;
    
    Deque_as_array *deck = new Deque_as_array(5);

    deck->enqueue_tail(6);
    deck->enqueue_tail(7);
    deck->enqueue_tail(8);
    deck->enqueue_tail(9);
    deck->dequeue_head();
    
    //Deque_as_array *deck2 = new Deque_as_array(10);
    
    cout<< deck->size() << endl;
    
    cout<< deck->capacity() << endl;
    
    cout<< deck->empty() << endl;
    
    deck->print();
    deck->clear();
    cout<< deck->size() << endl;
    
    cout<< deck->capacity() << endl;
    
    cout<< deck->empty() << endl;
    deck->enqueue_tail(6);
    deck->enqueue_tail(7);
    deck->enqueue_tail(8);
    deck->enqueue_tail(9);
    
    deck->dequeue_head();
    

    deck->print();
	cout << "Starting Test Run" << std::endl;

	tester.run();

	cout << "Finishing Test Run" << std::endl;

	return 0;
}